version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: AccountingDemoAPI/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    # Removed database dependency since it's commented out

  webapp:
    build:
      context: .
      dockerfile: WebApp/Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - api

  # Optional: Add a database service for development
  # database:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=YourStrong@Passw0rd
  #   ports:
  #     - "1433:1433"
  #   volumes:
  #     - sqlserver_data:/var/opt/mssql

# volumes:
#   sqlserver_data: 